### ISSUE TITLE
repository checkout problem on Windows

### ISSUE THREAD

**Issue by DenisPolygalov** [FormalTheology/GoedelGod#15]
Hi. Fist of all thanks for this very interesting work and opportunity to open an issue on God's existence :) The problem is that some files in this repository contain colon ":" characters in their names therefore leading to problems on Windows:

$ git clone https://github.com/FormalTheology/GoedelGod.git
Cloning into 'GoedelGod'...
remote: Enumerating objects: 8895, done.
remote: Total 8895 (delta 0), reused 0 (delta 0), pack-reused 8895
Receiving objects: 100% (8895/8895), 444.74 MiB | 2.05 MiB/s, done.
Resolving deltas: 100% (5669/5669), done.
error: unable to create file Talks/2015/Tableaux/DemoMaterial/DEMO-THF/RESULTS-2                                                                                     015-07-23--18:04:50: Invalid argument
error: unable to create file Talks/2015/Tableaux/DemoMaterial/DEMO-THF/RESULTS-2                                                                                     015-07-23--18:05:04: Invalid argument
error: unable to create file Talks/2015/Tableaux/DemoMaterial/DEMO-THF/RESULTS-2                                                                                     015-07-31--13:25:43: Invalid argument
error: unable to create file Talks/2015/Tableaux/DemoMaterial/DEMO-THF/RESULTS-2                                                                                     015-07-31--14:01:08: Invalid argument
Checking out files: 100% (1188/1188), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

Here is description of similar problem:
https://stackoverflow.com/questions/5991805/how-do-i-clone-files-with-colons-in-the-filename 

It will be helpful if you can rename (replace colon with underscore for example) these 4 files by using 'git mv' command and push changes to the github.com

Thanks,
Denis.

**Comment by Zahnentferner** [comment]
@DenisPolygalov , thanks! And thanks for your interest in this work. I have renamed the problematic files. I would like to apologize for the delay. I was on holidays.
