### ISSUE TITLE
Don't see the third alternative

### ISSUE THREAD

**Issue by nydehi** [FormalTheology/GoedelGod#6]
I think there is a third alternative that I don't see really anywhere. Namely, that God's existence may be rationally indeterminate. His existence is neither provable nor  demonstrably false via reason. 

The fundamental thesis I am making is that a universe of meaning is empirically indistinguishable from one that is meaningless.  

 A God would give an absolute meaning to everything.  But We only know the meanings that  we assign. There is no empirical test for the existence of an absolute meaning.  Therefore it is indeterminate. So if we can not determine there is an absolute meaning for an object we cannot determine the existence of a God.

To say it is empirically impossible to determine whether or not the universe has meaning means God's existence cannot be shown via reason.

**Comment by nydehi** [comment]
Well from another angle, Kant believed that there was synthetic apriori statements.  He thought that math etc were examples.  However, given what I wrote above I would like to say that synthetic apriori statements are statements on our limits of knowledge.Specifically disjunctive statement of this or that. ie here the world has an universal absolute meaning to everything or it doesn't. ie it has only meaning assigned to it on a case by case basis that is transient. so meaning here is what is experienced or assigned the observer   We can not perform an experiement to determine which is true but see immediately one or the other is true without being able to say which. hence it is synthetic apriori.  I am still working out about the different senses of meaning. but I think this approach is better then move on to God

**Comment by tcanascimento** [comment]
Let me see: what nydehi is calling for is something like a "incompleteness proof" for God's existence - is that right?
The concept of God plays a heuristic role on Kant's theory of practical reason; you may think about synthetic judgments (like Husserl does after Kant), but it is not the point with the proofs we dealing with (ps.: Kant was wrong about seeing math in synthetic way). If you want to follow Kant's synthetic theory, you will fall into a kind of Wittgensteinian Tractatus's World, where only that can be said can be thought of - ie, the structure of language rules the world - everything besides that is "Das Mystiche". That does not work (Wittegenstein sought that as well Carnap's Aufbau project... :-D)... From logical point of view, St Anselm's proof is right...

**Comment by nydehi** [comment]
I am as of this moment saying my essential idea outlined in first post would be better pursued by a continental approach and not an analytic one. as for Kant being wrong about the status of math I would agree.
All I am saying here is the following:
a) there is absolute meaning or there isn't absolute meaning
b) this is seen to be true with no reference to science or philosophy or religion
c) it is ascertainable to be true by only introspection and thought. 
d) this a disjunctive statement on our limit of knowledge that is synthetic a priori

So all that those other points about Kant or Wittgenstein is not relevant at what I am calling step 1 on my road map.  and at this point there is no mention of God at all.

**Comment by Ceilican** [comment]
"A or not A" is considered valid in classical logic for any A, including "A = there is absolute meaning". This is known as the principle of excluded middle. On the other hand, there are logics where this principle is rejected. Intuitionistic logics are the most famous examples.

**Comment by nydehi** [comment]
you are mistaking form for substance. I could have easily stated instead that 
it is indeterminate that there is universal meaning and it is indeterminate that there is only local meaning.  this indeterminacy is relevant and synthetic a priori.  this is not a trivial A or not A statement.

**Comment by Ceilican** [comment]
Your statement "there is absolute meaning or there isn't absolute meaning" is clearly of the form "A or not A". You are free to state whatever you want, but what you stated originally is undeniably and unmistakably of the form "A or not A".

Your rephrased statement in the comment above is, on the other hand, clearly not of the form "A and not A". Without further clarification about what you mean by "indeterminate", "universal", "local" and "meaning", so that we could share a common ground, there is not much I could say about it. But, anyway, I feel that this discussion is going away from my own areas of interest and I wouldn't be interested in saying more about it anyway. So, don't worry about clarifying these concepts to me. As long as they are clear enough to you, I am happy for you.
